Search Screen
gabrielpdsilva/westerosApp pull request #1
Opened 2021-03-10 15:02 UTC by gabrielpdsilva

Starting with the development of the first screen (Search).

2021-03-10 15:12 UTC, Victor-Bueno requested changes
Fora esse detalhe está bacana

2021-03-10 15:12 UTC, Victor-Bueno commented on src/screens/SearchScreen.js
> +            />
Ao lado do TextInput deveria ter um botão pra confirmar a busca né? Aquela lupinha do design
Ah e aqui seria onde você poderia adicionar o comentário, algo como:
```javascript
<TextInput // TODO Change this component to a picker
...
```

2021-03-10 16:43 UTC, reberthkss approved these changes
Tirando aquele comentário do Victor, por mim está ok!

2021-03-10 16:55 UTC, iuricernov approved these changes
Deixando aprovado tb, só pendente o comment do Victor

2021-03-10 16:55 UTC, iuricernov commented on App.js
> +    <SearchScreen/>
Aqui vai precisar implementar um navigation né? Aí tb dá para fazer em um próximo PR

2021-03-10 16:55 UTC, iuricernov commented on src/screens/SearchScreen.js
> +            />
PS - Nesse formato acima não vai funcionar, acho que o // não pega dentro do "xml".

2021-03-10 17:02 UTC, yuri-akira approved these changes

2021-03-10 17:08 UTC, Victor-Bueno commented on src/screens/SearchScreen.js
> +            />
Ah simm, disfarça kk 🤦🏻‍♂️

2021-03-11 15:55 UTC, reberthkss approved these changes

2021-03-11 16:24 UTC, Victor-Bueno approved these changes
Só uma dica, normalmente quanto mais você dividir as alterações em commits menores melhor é. Então no caso de mudanças requisitadas no review, normalmente fazemos um commit pra cada mudança pedida, no seu caso poderiam até ser dois commits se quisesse, um para a tela de busca e outra para a implementação da stack.
Organizar os commits, ter uma boa descrição de PRs, entre outras coisas ajuda muito a revisão do código.

2021-03-11 16:29 UTC, iuricernov commented
Atenção: não mandar novas features para o mesmo PR. Nesse caso, vi que adicionou o picker, mas a ideia era mandar isso em um PR posterior.
Daria um certo trabalho reverter, então dá para seguir por enquanto

2021-03-11 16:43 UTC, yuri-akira approved these changes

2021-03-11 19:26 UTC, iuricernov approved these changes
Tinha esquecido de aprovar 😅

2021-03-12 10:59 UTC, merged